version: "3"

services:
  consul-dev:
    image: consul:1.13.2
    container_name: consul
    # The UDP port 8600 is used by Consul nodes to talk to each other, so
    # it's good to add it here even though we're using a single-node setup.
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -server -ui -node=server-1 -bootstrap-expect=1 -client="0.0.0.0"'
    networks:
      - microservices
  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '5673:5673'
      - '15672:15672'
    networks:
      - microservices
networks:
  microservices:
    driver: bridge

